version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 8080:15672
      - 5672:5672